version: "3.0"
services:
  dockerapp:
    image: netasankara/poc-docker-ci-py:2cbe0e984298287a46eb0e821bbe83a0c5159c16
    ports:
      - "5000:5000"
    depends_on:
      - redis
    deploy:
      replicas : 10
  dockerapp_failover:
    image: netasankara/poc-docker-ci-py:2cbe0e984298287a46eb0e821bbe83a0c5159c16
    ports:
      - "4000:5000"
    depends_on:
      - redis
    deploy:
      replicas : 10
  redis:
    image: redis:3.2.0